// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Version3OfERP21_8System.Models.InvoiceContext;

#nullable disable

namespace Version3OfERP21_8System.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20250828100144_IntialCreateNo1N")]
    partial class IntialCreateNo1N
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Version3OfERP21_8System.Models.Collector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Collectors");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Invoices_and_supplier.CashInvoice", b =>
                {
                    b.Property<int>("CashInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SuppliersName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Total_price")
                        .HasColumnType("double");

                    b.Property<int>("suppliersId")
                        .HasColumnType("int");

                    b.HasKey("CashInvoiceId");

                    b.HasIndex("suppliersId");

                    b.ToTable("CashInvoices");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Invoices_and_supplier.Due_billsInvoice", b =>
                {
                    b.Property<int>("Due_billsInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Duepercentage")
                        .HasColumnType("double");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SuppliersName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Total_price")
                        .HasColumnType("double");

                    b.Property<int>("suppliersId")
                        .HasColumnType("int");

                    b.HasKey("Due_billsInvoiceId");

                    b.HasIndex("suppliersId");

                    b.ToTable("Due_BillsInvoices");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Invoices_and_supplier.Return_to_Supplier", b =>
                {
                    b.Property<int>("Return_to_SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SuppliersName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Total_price")
                        .HasColumnType("double");

                    b.Property<int>("suppliersId")
                        .HasColumnType("int");

                    b.HasKey("Return_to_SupplierId");

                    b.HasIndex("suppliersId");

                    b.ToTable("Return_To_Suppliers");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Invoices_and_supplier.Suppliers_cash", b =>
                {
                    b.Property<int>("Suppliers_cashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SuppliersName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Supplly_Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Supplly_Price")
                        .HasColumnType("double");

                    b.Property<DateTime>("SupplyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("suppliersId")
                        .HasColumnType("int");

                    b.HasKey("Suppliers_cashId");

                    b.HasIndex("suppliersId");

                    b.ToTable("Suppliers_Cashes");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Invoices_and_supplier.ruinInvoice", b =>
                {
                    b.Property<int>("ruinInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ruinInvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ruinInvoiceId");

                    b.ToTable("RuinInvoices");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.MainRegions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MainRegionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("start_Number")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("MainRegions");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Main_purchase_price")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Percentage_Representative")
                        .HasColumnType("double");

                    b.Property<double>("Sale_purchase_price")
                        .HasColumnType("double");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Representative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("user_Number")
                        .HasColumnType("int");

                    b.Property<int>("user_Password")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Representatives");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Storekeepers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("user_Number")
                        .HasColumnType("int");

                    b.Property<int>("user_Password")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Storekeepers");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.SubRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MainRegionId")
                        .HasColumnType("int");

                    b.Property<string>("MainRegionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("mainRegionsId")
                        .HasColumnType("int");

                    b.Property<string>("subRegionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("mainRegionsId");

                    b.ToTable("SubRegions");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Suppliers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Invoices_and_supplier.CashInvoice", b =>
                {
                    b.HasOne("Version3OfERP21_8System.Models.Suppliers", "suppliers")
                        .WithMany("suppliers")
                        .HasForeignKey("suppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("suppliers");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Invoices_and_supplier.Due_billsInvoice", b =>
                {
                    b.HasOne("Version3OfERP21_8System.Models.Suppliers", "suppliers")
                        .WithMany("due_BillsInvoices")
                        .HasForeignKey("suppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("suppliers");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Invoices_and_supplier.Return_to_Supplier", b =>
                {
                    b.HasOne("Version3OfERP21_8System.Models.Suppliers", "suppliers")
                        .WithMany("return_To_Suppliers")
                        .HasForeignKey("suppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("suppliers");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Invoices_and_supplier.Suppliers_cash", b =>
                {
                    b.HasOne("Version3OfERP21_8System.Models.Suppliers", "suppliers")
                        .WithMany("Suppliers_cash")
                        .HasForeignKey("suppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("suppliers");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.SubRegion", b =>
                {
                    b.HasOne("Version3OfERP21_8System.Models.MainRegions", "mainRegions")
                        .WithMany("subRegions")
                        .HasForeignKey("mainRegionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mainRegions");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.MainRegions", b =>
                {
                    b.Navigation("subRegions");
                });

            modelBuilder.Entity("Version3OfERP21_8System.Models.Suppliers", b =>
                {
                    b.Navigation("Suppliers_cash");

                    b.Navigation("due_BillsInvoices");

                    b.Navigation("return_To_Suppliers");

                    b.Navigation("suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
